a=int(input('Month: '))
if a==1: print('January - 31 days')
elif a==2: print('Febuary - 28 or 29 days')
elif a==3:print('March - 31 days')
elif a==4:print('April - 30 days')
elif a==5:print('May - 31 days')
elif a==6:print('June - 30 days')
elif a==7:print('July - 31 days')
elif a==8:print('August - 31 days')
elif a==9:print('September - 30 days')
elif a==10:print('October - 31 days')
elif a==11:print('November - 30 days')
elif a==12:print('December - 31 days')